// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package university_management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UniversityManagementServiceClient is the client API for UniversityManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UniversityManagementServiceClient interface {
	GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...grpc.CallOption) (*GetDepartmentResponse, error)
	GetStudents(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*GetStudentResponse, error)
	CaptureUserSignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	CaptureUserSignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type universityManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUniversityManagementServiceClient(cc grpc.ClientConnInterface) UniversityManagementServiceClient {
	return &universityManagementServiceClient{cc}
}

func (c *universityManagementServiceClient) GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...grpc.CallOption) (*GetDepartmentResponse, error) {
	out := new(GetDepartmentResponse)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetDepartment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) GetStudents(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*GetStudentResponse, error) {
	out := new(GetStudentResponse)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/GetStudents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) CaptureUserSignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/CaptureUserSignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityManagementServiceClient) CaptureUserSignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/university_management.UniversityManagementService/CaptureUserSignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UniversityManagementServiceServer is the server API for UniversityManagementService service.
// All implementations must embed UnimplementedUniversityManagementServiceServer
// for forward compatibility
type UniversityManagementServiceServer interface {
	GetDepartment(context.Context, *GetDepartmentRequest) (*GetDepartmentResponse, error)
	GetStudents(context.Context, *GetStudentRequest) (*GetStudentResponse, error)
	CaptureUserSignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	CaptureUserSignOut(context.Context, *SignOutRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedUniversityManagementServiceServer()
}

// UnimplementedUniversityManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUniversityManagementServiceServer struct {
}

func (UnimplementedUniversityManagementServiceServer) GetDepartment(context.Context, *GetDepartmentRequest) (*GetDepartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartment not implemented")
}
func (UnimplementedUniversityManagementServiceServer) GetStudents(context.Context, *GetStudentRequest) (*GetStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudents not implemented")
}
func (UnimplementedUniversityManagementServiceServer) CaptureUserSignIn(context.Context, *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureUserSignIn not implemented")
}
func (UnimplementedUniversityManagementServiceServer) CaptureUserSignOut(context.Context, *SignOutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureUserSignOut not implemented")
}
func (UnimplementedUniversityManagementServiceServer) mustEmbedUnimplementedUniversityManagementServiceServer() {
}

// UnsafeUniversityManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UniversityManagementServiceServer will
// result in compilation errors.
type UnsafeUniversityManagementServiceServer interface {
	mustEmbedUnimplementedUniversityManagementServiceServer()
}

func RegisterUniversityManagementServiceServer(s grpc.ServiceRegistrar, srv UniversityManagementServiceServer) {
	s.RegisterService(&UniversityManagementService_ServiceDesc, srv)
}

func _UniversityManagementService_GetDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetDepartment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetDepartment(ctx, req.(*GetDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_GetStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).GetStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/GetStudents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).GetStudents(ctx, req.(*GetStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_CaptureUserSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).CaptureUserSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/CaptureUserSignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).CaptureUserSignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityManagementService_CaptureUserSignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityManagementServiceServer).CaptureUserSignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_management.UniversityManagementService/CaptureUserSignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityManagementServiceServer).CaptureUserSignOut(ctx, req.(*SignOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UniversityManagementService_ServiceDesc is the grpc.ServiceDesc for UniversityManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UniversityManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "university_management.UniversityManagementService",
	HandlerType: (*UniversityManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDepartment",
			Handler:    _UniversityManagementService_GetDepartment_Handler,
		},
		{
			MethodName: "GetStudents",
			Handler:    _UniversityManagementService_GetStudents_Handler,
		},
		{
			MethodName: "CaptureUserSignIn",
			Handler:    _UniversityManagementService_CaptureUserSignIn_Handler,
		},
		{
			MethodName: "CaptureUserSignOut",
			Handler:    _UniversityManagementService_CaptureUserSignOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "university-management.proto",
}
